[SCRIPTCASE]  
URL=https://localhost/telematica/suricato.exe
APP_PATH=C:\Telematica\Suricato\suricato\app  
BASE_URL=https://localhost/suricato/app
USUARIO=ADMIN
SENHA=Suricato200@!
HEADLESS=True  
TIMEOUT=10000
SCREENSHOT_PATH=screenshots
SCREENSHOT_MODE=ALL
; NONE
; ERROR
; ALL