[MONITOR]

# 0 = Executa todas as aplicações
MAX_APPS=25

# ASC ou DESC
ORDER=ASC

# True = Executa apenas aplicações habilitadas abaixo
# False = Ignora os filtros e executa todas
ONLY_ENABLED=False



[SCREENSHOT]

# NONE
# ERROR
# ALL
MODE=ERROR


[FILTROS]

frmColaborador=True
cnsColaborador=True
frmEmpresas=True
cnsEmpresas=True
frmGrupoAcesso=True
cnsGrupoREP=True

heartbeat=False
logon=False
applet=False